run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - promlinter
    - revive
    - staticcheck
    - unconvert
    - unused