name: continuous-integration

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  GO_VERSION: "^1.23"

jobs:
  ci-go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: ./...
